services:
  airflow-db:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - airflow_db:/var/lib/postgresql/data

  mysql:
    image: mysql:8.0
    container_name: project-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yt
      MYSQL_USER: ytuser
      MYSQL_PASSWORD: ytpw
    ports:
      - "3308:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -proot --silent"]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - mysql_data:/var/lib/mysql

  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    image: airflow-ml:latest
    command: webserver
    env_file:
      - ./airflow/.env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db/airflow
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"
      PYTHONPATH: /opt/airflow/dags
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/requirements.txt:/requirements.txt
    depends_on:
      - airflow-db
      - mysql

  airflow-scheduler:
    image: airflow-ml:latest
    command: scheduler
    env_file:
      - ./airflow/.env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db/airflow
      PYTHONPATH: /opt/airflow/dags
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/requirements.txt:/requirements.txt
    depends_on:
      - airflow-db
      - mysql

  airflow-init:
    image: airflow-ml:latest
    entrypoint: bash -c "airflow db init && airflow users create --username admin --password admin --firstname a --lastname a --role Admin --email a@a.a && /bin/true"
    env_file:
      - ./airflow/.env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db/airflow
    volumes:
      - ./airflow/requirements.txt:/requirements.txt
    depends_on:
      - airflow-db
      - mysql

volumes:
  airflow_db: {}
  mysql_data: {}
