"""init tables

Revision ID: 53b9a6408499
Revises: 
Create Date: 2025-10-09 17:21:57.520561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53b9a6408499'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('keyword', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('videos', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queries_keyword'), 'queries', ['keyword'], unique=False)
    # videos
    op.create_table('videos',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('channel_id', sa.String(length=64), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # video_stats
    op.create_table('video_stats',
    sa.Column('video_id', sa.String(length=32), nullable=False),
    sa.Column('view_count', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('video_id')
    )
    # comments
    op.create_table('comments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('video_id', sa.String(length=32), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    op.drop_table('video_stats')
    op.drop_table('videos')
    op.drop_index(op.f('ix_queries_keyword'), table_name='queries')
    op.drop_table('queries')
    # ### end Alembic commands ###
